### ISSUE TITLE
How to connect it to transformator

### ISSUE THREAD

**Issue by Almaz1c** [newAM/DevBoard_NCP1090#1]
Hi!
Can you explain how to properly connect this board to Ethernet transformator please?

**Comment by newAM** [comment]
The specific connections will depend on the pulse transformer you buy.  The data sheet for your transformer should mention it, if it does not then it probably does not have 802.3af support.

I used it in a project here if you're interested in a full schematic, I went the easy route and bought a magjack with it all built in.
https://github.com/newAM/FanController/blob/master/FanController_KiCAD_Schematic.pdf
